# Generated by Django 3.0.6 on 2020-05-07 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('type', models.CharField(max_length=150, null=True)),
                ('color', models.CharField(max_length=150, null=True)),
                ('power_supply', models.CharField(max_length=150, null=True)),
                ('side_panel_window', models.CharField(max_length=150, null=True)),
                ('external_5_25_bays', models.IntegerField(null=True)),
                ('external_3_5_bays', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('model', models.CharField(max_length=150, null=True)),
                ('series', models.CharField(max_length=150, null=True)),
                ('socket', models.CharField(max_length=150, null=True)),
                ('core_count', models.IntegerField(null=True)),
                ('core_clock', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CpuCooler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('fan_rpm', models.CharField(blank=True, max_length=150, null=True)),
                ('noise_level', models.CharField(blank=True, max_length=150, null=True)),
                ('color', models.CharField(blank=True, max_length=150, null=True)),
                ('radiator_size', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('speed', models.CharField(max_length=150, null=True)),
                ('type', models.CharField(max_length=150, null=True)),
                ('modules_count', models.IntegerField(null=True)),
                ('modules_memory', models.IntegerField(null=True)),
                ('cas_latency', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('socket', models.CharField(max_length=150, null=True)),
                ('form_factor', models.CharField(max_length=150, null=True)),
                ('memory_max', models.IntegerField(null=True)),
                ('memory_slots', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('form_factor', models.CharField(max_length=150, null=True)),
                ('efficiency_rating', models.CharField(max_length=150, null=True)),
                ('wattage', models.IntegerField(null=True)),
                ('modular', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('capacity', models.CharField(max_length=150, null=True)),
                ('type', models.CharField(max_length=150, null=True)),
                ('cache', models.CharField(blank=True, max_length=150, null=True)),
                ('form_factor', models.CharField(max_length=150, null=True)),
                ('interface', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('chipset', models.CharField(max_length=150, null=True)),
                ('memory', models.CharField(max_length=150, null=True)),
                ('core_clock', models.IntegerField(null=True)),
                ('interface', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.Case')),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.Cpu')),
                ('cpu_cooler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.CpuCooler')),
                ('memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.Memory')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.Motherboard')),
                ('psu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.PowerSupply')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.Storage')),
                ('video_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.VideoCard')),
            ],
        ),
    ]
