# Generated by Django 3.0.6 on 2020-05-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
