# Generated by Django 3.0.6 on 2020-05-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_computer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='description',
            field=models.CharField(max_length=750, null=True),
        ),
    ]
