# Generated by Django 3.0.6 on 2020-05-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_auto_20200507_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='core_clock',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='core_clock',
            field=models.FloatField(null=True),
        ),
    ]
