# Generated by Django 3.0.6 on 2020-05-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0005_auto_20200507_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='memory',
            field=models.ManyToManyField(to='computers.Memory'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage',
            field=models.ManyToManyField(to='computers.Storage'),
        ),
    ]
