# Generated by Django 3.0.6 on 2020-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0008_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
