# Generated by Django 3.0.6 on 2020-05-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0010_auto_20200513_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
