# Generated by Django 3.0.6 on 2020-05-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0012_auto_20200518_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
    ]
