# Generated by Django 3.0.6 on 2020-05-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0013_remove_order_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
