# Generated by Django 3.0.6 on 2020-05-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0016_auto_20200519_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Send out', 'Відправлено'), ('Pending', 'Очікує на відправлення')], default='Pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
