# Generated by Django 3.0.6 on 2020-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0017_auto_20200519_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
