# Generated by Django 3.0.6 on 2020-05-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0019_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
