# Generated by Django 3.0.6 on 2020-05-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0020_auto_20200519_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='twice_price',
            field=models.FloatField(null=True),
        ),
    ]
