# Generated by Django 3.0.6 on 2020-05-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0021_cpu_twice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='twice_price',
        ),
    ]
