# Generated by Django 3.0.6 on 2020-05-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0023_computer_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='external_3_5_bays',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='external_5_25_bays',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='core_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='cas_latency',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='modules_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='modules_memory',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='memory_max',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='memory_slots',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='wattage',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
